-- MySQL Script generated by MySQL Workbench
-- 09/16/19 09:08:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema progme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema progme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `progme` DEFAULT CHARACTER SET utf8 ;
USE `progme` ;

-- -----------------------------------------------------
-- Table `progme`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Usuário` (
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `é_Aluno` TINYINT(1) NOT NULL,
  `Matrícula` INT NOT NULL,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Senha_UNIQUE` (`Senha` ASC),
  PRIMARY KEY (`Matrícula`),
  UNIQUE INDEX `Matrícula_UNIQUE` (`Matrícula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progme`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Agenda` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Usuário_Matrícula` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuário_Matrícula`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Agenda_Usuário1_idx` (`Usuário_Matrícula` ASC),
  CONSTRAINT `fk_Agenda_Usuário1`
    FOREIGN KEY (`Usuário_Matrícula`)
    REFERENCES `progme`.`Usuário` (`Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progme`.`Workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Workshop` (
  `NomeWorkshop` VARCHAR(45) NOT NULL,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Local` VARCHAR(100) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NomeWorkshop_UNIQUE` (`NomeWorkshop` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progme`.`Agenda_has_Workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Agenda_has_Workshop` (
  `Agenda_ID` INT NOT NULL,
  `Workshop_ID` INT NOT NULL,
  PRIMARY KEY (`Agenda_ID`, `Workshop_ID`),
  INDEX `fk_Agenda_has_Workshop_Workshop1_idx` (`Workshop_ID` ASC),
  INDEX `fk_Agenda_has_Workshop_Agenda1_idx` (`Agenda_ID` ASC),
  CONSTRAINT `fk_Agenda_has_Workshop_Agenda1`
    FOREIGN KEY (`Agenda_ID`)
    REFERENCES `progme`.`Agenda` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agenda_has_Workshop_Workshop1`
    FOREIGN KEY (`Workshop_ID`)
    REFERENCES `progme`.`Workshop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progme`.`Usuário_has_Workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Usuário_has_Workshop` (
  `Usuário_Matrícula` INT NOT NULL,
  `Workshop_ID` INT NOT NULL,
  PRIMARY KEY (`Usuário_Matrícula`, `Workshop_ID`),
  INDEX `fk_Usuário_has_Workshop_Workshop1_idx` (`Workshop_ID` ASC),
  INDEX `fk_Usuário_has_Workshop_Usuário1_idx` (`Usuário_Matrícula` ASC),
  CONSTRAINT `fk_Usuário_has_Workshop_Usuário1`
    FOREIGN KEY (`Usuário_Matrícula`)
    REFERENCES `progme`.`Usuário` (`Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Workshop_Workshop1`
    FOREIGN KEY (`Workshop_ID`)
    REFERENCES `progme`.`Workshop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `progme`.`Agenda_has_Workshop1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `progme`.`Agenda_has_Workshop1` (
  `Agenda_ID` INT NOT NULL,
  `Agenda_Usuário_Matrícula` INT NOT NULL,
  `Workshop_ID` INT NOT NULL,
  PRIMARY KEY (`Agenda_ID`, `Agenda_Usuário_Matrícula`, `Workshop_ID`),
  INDEX `fk_Agenda_has_Workshop1_Workshop1_idx` (`Workshop_ID` ASC),
  INDEX `fk_Agenda_has_Workshop1_Agenda1_idx` (`Agenda_ID` ASC, `Agenda_Usuário_Matrícula` ASC),
  CONSTRAINT `fk_Agenda_has_Workshop1_Agenda1`
    FOREIGN KEY (`Agenda_ID` , `Agenda_Usuário_Matrícula`)
    REFERENCES `progme`.`Agenda` (`ID` , `Usuário_Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agenda_has_Workshop1_Workshop1`
    FOREIGN KEY (`Workshop_ID`)
    REFERENCES `progme`.`Workshop` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * from usuario;
SELECT DataMarcada from workshop;
INSERT INTO usuario VALUES ("Renzo", 'renzo@inatel.br', 001366, false, 366);
INSERT INTO workshop VALUES ("Swift", '2019-12-12 15:30', 'CDG Treinamentos', Id, 22);
INSERT INTO workshop VALUES ("R", '2019-12-14 17:30', 'CDG Treinamentos', Id, 22);
INSERT INTO workshop VALUES ("Swift", '2019-12-12 15:30', 'CDG Treinamentos');
INSERT INTO workshop (Avaliacao) VALUES ('https://www.youtube.com/watch?v=KSgNyZXPMXc');
SELECT * from usuario WHERE Nome LIKE "Renzo";
ALTER TABLE workshop auto_increment = 1;
SELECT * from workshop;
SELECT * FROM workshop WHERE NomeWorkshop LIKE 'Java';
UPDATE workshop SET Local = 'CDG TREINAMENTOS EH BRABO DIMAIS' WHERE Id = 10;
DELETE FROM workshop WHERE Id = 16;

SELECT * from usuario_has_workshop;
INSERT INTO usuario_has_workshop VALUES (1478,10, 72, 'Tchurubango tchurusbago');
INSERT INTO usuario_has_workshop VALUES (1341,1, 60, 'Achei mediocre');
INSERT INTO usuario_has_workshop VALUES (3211,1, 43, 'Monitores fracos :(');
INSERT INTO usuario_has_workshop VALUES (1519,9);
INSERT INTO usuario_has_workshop VALUES (1519,12);
INSERT INTO usuario_has_workshop VALUES (1519,13);
SELECT * from usuario_has_workshop WHERE Usuario_Matricula = 1519;
SELECT * FROM workshop WHERE Id = 11 OR Id = 22;
SELECT * FROM workshop WHERE Id NOT IN (9,12);
SELECT * FROM workshop WHERE workshop.Id IN (SELECT Workshop_Id FROM usuario_has_workshop WHERE Usuario_Matricula = 1519);
UPDATE workshop SET Avaliacao = 'https://www.youtube.com/watch?v=KSgNyZXPMXc' WHERE Id > 0;
UPDATE usuario_has_workshop SET NotaAvaliada = 80, Comentario = 'Muito bom!' WHERE Usuario_Matricula = 1519 AND Workshop_Id = 1;
SELECT NotaAvaliada FROM usuario_has_workshop WHERE Usuario_Matricula = 1519 AND Workshop_Id = 1;

DELETE FROM usuario_has_workshop WHERE Usuario_Matricula = 1519;
SELECT * FROM workshop WHERE workshop.Id NOT IN (SELECT Workshop_Id FROM usuario_has_workshop WHERE Usuario_Matricula = 1519);
SELECT Nome FROM usuario WHERE Matricula IN (SELECT Usuario_Matricula FROM usuario_has_workshop WHERE Workshop_Id = 1);
SELECT * FROM usuario_has_workshop WHERE Workshop_Id = 1;